### ISSUE TITLE
Week of 01-03, New Years Code Warmup

### ISSUE THREAD

**Issue by LindaLiu1202** [PrishaB/Team2Reunion#1]
**Team Review ticket, tangible artifacts, Github commits, and team/self-grade on each individual**
- #3 
- #2 
- #4 
- [Scrumboard](https://github.com/users/PrishaB/projects/1)
- [Commits](https://github.com/PrishaB/Team2Reunion/commits/gh-pages)
- [Commits](https://github.com/Lychee80/Lychee80.github.io/commits/gh-pages)
- [Deployment issue](https://github.com/Lychee80/t2_spring_8192/issues/1)
- [Frontend website](https://lychee80.github.io)
- [Backend website](https://serafina.tk)

**Deployment**
  - [x] deploying APIs from the spring project using AWS
  - <img width="200" height="300" alt="image" src="https://user-images.githubusercontent.com/89223976/211381320-510e1e01-34ed-462f-ad01-eb793eb1edf7.jpeg">
  - [x] building GitHub page frontend project talk APIs to the spring project
  - [x]  fetch JSON and present JSON

**Frontend**
  - [x] start project design by adding and removing items from the Template
  - [x] basic frontend work for APIs
  - [x] Frontend and backend communicate 👌 
(Make sure not to run the link on school WI-FI because the APIs will not work)

- [x] Each person needs to show that they can run the project locally

**Tasks of each member**

| Name | Role | Grade | Notes |
| ---------- | --------- | ----- | -------------------------------|
| Prisha | Frontend | 2.7/3 | Was responsible for FRQ frontend work and fixed frontend for all of the APIs. |
| Serafina | DevOps | 2.7/3 | Worked on Deployment of backend and fixed frontend error where pages would not show up. Helped on Frqs |
| Divya | Scrum Master | 2.7/3 | Worked on Lightboard frq and helped with the frontend on the pages, helped with the review ticket|
| Linda | Backend | 2.7/3 | Helped on frq work, customized reunion project (edit home.html and index.html) |

**Comment by LindaLiu1202** [comment]
![D3E735FF-B650-421B-BA0B-021A31232629](https://user-images.githubusercontent.com/89223976/211381320-510e1e01-34ed-462f-ad01-eb793eb1edf7.jpeg)
